---
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_14_petacular
    ports:
      - "54321:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: petacular_user
      POSTGRES_PASSWORD: petacular_123
